apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
spec:
  project: default
  source:
    chart: petclinic_chart_local
    targetRevision: "1"
    repoURL: https://raw.githubusercontent.com/ersinsari13/chart-repo/dev
    helm:
      releaseName: petclinic
  destination:
    server: "https://kubernetes.default.svc"
    namespace: myapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
