apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: grafana-server
  name: grafana-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana-server
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/k8s-default: "true"
        io.kompose.service: grafana-server
    spec:
      containers:
        - image: '{{ .Values.IMAGE_TAG_GRAFANA_SERVICE }}'
          name: grafana-server
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
status: {}