apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: grafana-server
  name: grafana-server
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
      nodePort: 30003
  selector:
    io.kompose.service: grafana-server
status:
  loadBalancer: {}