apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: prometheus-server
  name: prometheus-server
spec:
  type: NodePort
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9090
      nodePort: 30002
  selector:
    io.kompose.service: prometheus-server
status:
  loadBalancer: {}